version: '3.9'
networks:
  backend:
    driver: bridge
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - backend
    restart: always

  api:
    container_name: breweries_ha
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
    restart: always
    networks:
      - backend